# ===========================
# Application Configuration
# ===========================
spring:
  application:
    name: loan-service

  # ===========================
  # Kafka Configuration
  # ===========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: credit-risk-group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javatechie
    username: root
    password: Password

  # ===========================
  # JPA / Hibernate Configuration
  # ===========================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Correct place for dialect property

# ===========================
# Server Configuration
# ===========================
server:
  port: 9191

# ===========================
# Kafka Topic Configuration
# ===========================
loan:
  processing:
    topic-name: loan-process-topic